services:
  database:
    container_name: database
    image: "postgres:16.2-alpine3.19"
    restart: always
    environment:
      POSTGRES_DB: MuscleBoost
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: